# Generated by Django 4.2.23 on 2025-07-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='full_name',
            field=models.CharField(default='defaut_name', max_length=100),
            preserve_default=False,
        ),
    ]
