# Generated by Django 4.2.23 on 2025-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0004_schedule_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='full_name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
