# Generated by Django 4.2.23 on 2025-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=200, unique=True),
        ),
    ]
