# Generated by Django 4.2.23 on 2025-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='Leave blank to auto-generate.', max_length=100),
            preserve_default=False,
        ),
    ]
