# Generated by Django 4.2.23 on 2025-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='default-slug-for-author', help_text='Leave blank to auto-generate.', max_length=100),
            preserve_default=False,
        ),
    ]
