# Generated by Django 4.2.23 on 2025-07-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate.', max_length=100, unique=True),
        ),
    ]
