# Generated by Django 4.2.23 on 2025-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_author_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counted_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
